module_name: Cross selling
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - cross selling
  - up sell
  - marketing
description_short: The cross selling module allows you to add a block to cross sell products.
description: description.md
images:
  - image-1.png
license: AFL